language: elixir

matrix:
  include:
    - otp_release: 20.0
      elixir: 1.6
    - otp_release: 21.0
      elixir: 1.7

script:
  - mix format --check-formatted
  - MIX_ENV=test mix coveralls.travis
